env               = "poc"
region            = "us-west-2"
key               = "test.tf"
project_name      = "aws-transfer-ot"
owner_tag         = "AWS Devops Test"
bucket            = "transferfam"